### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by 2d4d** [ace-ecosystem/yara_scanner#8]
are you aware, that there are lots of yara rules in https://github.com/Neo23x0/signature-base/tree/master/yara which also contain metadata conditions, but with slightly different names, e.g. "filename" and "extension". if you would adopt that, your users could use all those rules without search & replace.

**Comment by seanmcfeely** [comment]
Hello, I know these are popular rulesets so I can look into creating cross-compatibility. However, it's not clear to me how the metadata conditions you've highlighted are being used. Do you know which program uses those metadata conditions? Can you point to an example rule? At a glance I only see "filename" and "extension" used in yara rule conditions... I do not see those used in the meta sections.

**Comment by 2d4d** [comment]
they're passed to yara from e.g. loki.py:
               # Yara Rule Match
                matches = rules.match(data=fileData,
                                      externals={
                                          'filename': fileName,
                                          'filepath': filePath,
                                          'extension': extension,
                                          'filetype': fileType,
                                          'md5': md5
                                      })

**Comment by 2d4d** [comment]
example rule: 
rule Cloaked_RAR_File {
    meta:
        description = "RAR file cloaked by a different extension"
        license = "https://creativecommons.org/licenses/by-nc/4.0/"
        author = "Florian Roth"
    condition:
        uint32be(0) == 0x52617221                           // RAR File Magic Header
        and not filename matches /(rarnew.dat|\.rar)$/is    // not the .RAR extension
        and not filepath contains "Recycle"                 // not a deleted RAR file in recycler
}

**Comment by seanmcfeely** [comment]
Ah, you're talking about using [external variables](https://github.com/VirusTotal/yara/blob/5a9efc471643c049123298e90946fb64d2f19fcd/docs/writingrules.rst#external-variables). Yara_scanner does support external variables but it doesn't implement the same logic that Loki scanner does to pass the same variables that a lot of the [Neo23x0/signature-base](https://github.com/Neo23x0/signature-base/) ruleset uses.

**Comment by unixfreak0037** [comment]
@2d4d thanks for the feedback here, we can see what we can do. In the past I've shied away from using external variables with yara rules because the standard yara command line tool requires the external vars to be defined if they exist in the rule set. So if you have a massive rule set and just one of the rules defines a "file_path" external variable, then the person running it must also define file_path even if what they are scanning has nothing to do with the rule that uses the external variable. This always put a burden on analysts who opt to use the command line yara tool to check their rules.

So what we chose to do some time ago was to define fields and values in the _meta_ section of the yara rule, and then this python wrapper interprets those in whatever way they are defined. In the end they have the same effect as using external variables but it does not force the user to define them when scanning with the rules.

Curious if you have ran into this issue, and if so, what kinds of solutions you've seen implemented for it.

We can certainly look at supporting the additional names in this library. It wouldn't hurt.
